//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Players18.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rating
    {
        public int Id { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 2)]
        public string Name { get; set; }

        [Range(0, 50)]
        public Nullable<int> Age { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 2)]
        public string Country { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 2)]
        public string Position { get; set; }

        [Required]
        [Display(Name = "Current Team")]
        [StringLength(40, MinimumLength = 2)]
        public string CurrentTeam { get; set; }

        [Display(Name = "Image")]
        public string ImageUrl { get; set; }

        [Display(Name = "Video")]
        public string VideoUrl { get; set; }
    }
}


